import { requireAdmin } from "@/app/data/admin/require-admin";
import { PaymentsClient } from "@/components/dashboard/payments/payments-client";
import type { PaymentWithRelations } from "@/components/dashboard/payments/payments-client";

/**
 * Platform Payments Page
 *
 * System-wide payment and revenue monitoring.
 * Track payments, subscriptions, and financial metrics across all organizations.
 */

// Calculate timestamps once at module level to avoid impure Date.now() during render
const now = Date.now();
const timestamps = {
  today: new Date(now).toISOString(),
  yesterday: new Date(now - 1000 * 60 * 60 * 24).toISOString(),
  twoDaysAgo: new Date(now - 1000 * 60 * 60 * 24 * 2).toISOString(),
  threeDaysAgo: new Date(now - 1000 * 60 * 60 * 24 * 3).toISOString(),
  oneWeekAgo: new Date(now - 1000 * 60 * 60 * 24 * 7).toISOString(),
  twoWeeksAgo: new Date(now - 1000 * 60 * 60 * 24 * 14).toISOString(),
};

export default async function PaymentsPage() {
  await requireAdmin();

  // TODO: Fetch real payments from database across ALL organizations
  // const payments = await prisma.payment.findMany({
  //   include: { contact: true, service: true, organization: true }
  // });

  // Mock payments data for demo - simulating multiple clinics
  const mockPayments = [
    {
      id: "pay_platform_1",
      organizationId: "org_wellness_nyc",
      ghlPaymentId: "ghl_inv_50001",
      ghlContactId: "ghl_contact_1001",
      contactId: null,
      serviceId: null,
      stripePaymentId: null,
      memberName: "Jennifer Smith",
      memberEmail: "jennifer.s@example.com",
      memberPhone: "+1 (212) 555-0001",
      amount: 200.0,
      status: "PAID",
      paymentMethod: "card",
      invoiceNumber: "NYC-2025-001",
      description: "NAD+ IV Therapy - Wellness NYC",
      paidAt: new Date(timestamps.today),
      createdAt: new Date(timestamps.today),
      updatedAt: new Date(timestamps.today),
      contact: null,
      service: null,
      organization: null,
    },
    {
      id: "pay_platform_2",
      organizationId: "org_wellness_la",
      ghlPaymentId: "ghl_inv_50002",
      ghlContactId: "ghl_contact_1002",
      contactId: null,
      serviceId: null,
      stripePaymentId: null,
      memberName: "Robert Chen",
      memberEmail: "robert.c@example.com",
      memberPhone: "+1 (310) 555-0002",
      amount: 175.0,
      status: "PAID",
      paymentMethod: "card",
      invoiceNumber: "LA-2025-001",
      description: "Hydration Therapy - Wellness LA",
      paidAt: new Date(timestamps.today),
      createdAt: new Date(timestamps.today),
      updatedAt: new Date(timestamps.today),
      contact: null,
      service: null,
      organization: null,
    },
    {
      id: "pay_platform_3",
      organizationId: "org_wellness_nyc",
      ghlPaymentId: "ghl_inv_50003",
      ghlContactId: "ghl_contact_1003",
      contactId: null,
      serviceId: null,
      stripePaymentId: null,
      memberName: "Maria Garcia",
      memberEmail: "maria.g@example.com",
      memberPhone: "+1 (212) 555-0003",
      amount: 225.0,
      status: "PENDING",
      paymentMethod: null,
      invoiceNumber: "NYC-2025-002",
      description: "Glutathione IV + B12 - Wellness NYC",
      paidAt: null,
      createdAt: new Date(timestamps.yesterday),
      updatedAt: new Date(timestamps.yesterday),
      contact: null,
      service: null,
      organization: null,
    },
    {
      id: "pay_platform_4",
      organizationId: "org_wellness_miami",
      ghlPaymentId: "ghl_inv_50004",
      ghlContactId: "ghl_contact_1004",
      contactId: null,
      serviceId: null,
      stripePaymentId: null,
      memberName: "David Johnson",
      memberEmail: "david.j@example.com",
      memberPhone: "+1 (305) 555-0004",
      amount: 150.0,
      status: "PAID",
      paymentMethod: "cash",
      invoiceNumber: "MIA-2025-001",
      description: "Myers Cocktail - Wellness Miami",
      paidAt: new Date(timestamps.yesterday),
      createdAt: new Date(timestamps.yesterday),
      updatedAt: new Date(timestamps.yesterday),
      contact: null,
      service: null,
      organization: null,
    },
    {
      id: "pay_platform_5",
      organizationId: "org_wellness_la",
      ghlPaymentId: "ghl_inv_50005",
      ghlContactId: "ghl_contact_1005",
      contactId: null,
      serviceId: null,
      stripePaymentId: null,
      memberName: "Sarah Williams",
      memberEmail: "sarah.w@example.com",
      memberPhone: "+1 (310) 555-0005",
      amount: 300.0,
      status: "PAID",
      paymentMethod: "card",
      invoiceNumber: "LA-2025-002",
      description: "Premium Wellness Package - Wellness LA",
      paidAt: new Date(timestamps.twoDaysAgo),
      createdAt: new Date(timestamps.twoDaysAgo),
      updatedAt: new Date(timestamps.twoDaysAgo),
      contact: null,
      service: null,
      organization: null,
    },
    {
      id: "pay_platform_6",
      organizationId: "org_wellness_nyc",
      ghlPaymentId: "ghl_inv_50006",
      ghlContactId: "ghl_contact_1006",
      contactId: null,
      serviceId: null,
      stripePaymentId: null,
      memberName: "Michael Brown",
      memberEmail: "michael.b@example.com",
      memberPhone: "+1 (212) 555-0006",
      amount: 175.0,
      status: "FAILED",
      paymentMethod: "card",
      invoiceNumber: "NYC-2025-003",
      description: "Hydration Therapy - Wellness NYC",
      paidAt: null,
      createdAt: new Date(timestamps.threeDaysAgo),
      updatedAt: new Date(timestamps.threeDaysAgo),
      contact: null,
      service: null,
      organization: null,
    },
    {
      id: "pay_platform_7",
      organizationId: "org_wellness_miami",
      ghlPaymentId: "ghl_inv_50007",
      ghlContactId: "ghl_contact_1007",
      contactId: null,
      serviceId: null,
      stripePaymentId: null,
      memberName: "Emily Davis",
      memberEmail: "emily.d@example.com",
      memberPhone: "+1 (305) 555-0007",
      amount: 250.0,
      status: "PAID",
      paymentMethod: "card",
      invoiceNumber: "MIA-2025-002",
      description: "Beauty Drip - Wellness Miami",
      paidAt: new Date(timestamps.threeDaysAgo),
      createdAt: new Date(timestamps.threeDaysAgo),
      updatedAt: new Date(timestamps.threeDaysAgo),
      contact: null,
      service: null,
      organization: null,
    },
    {
      id: "pay_platform_8",
      organizationId: "org_wellness_la",
      ghlPaymentId: "ghl_inv_50008",
      ghlContactId: "ghl_contact_1008",
      contactId: null,
      serviceId: null,
      stripePaymentId: null,
      memberName: "James Wilson",
      memberEmail: "james.w@example.com",
      memberPhone: "+1 (310) 555-0008",
      amount: 200.0,
      status: "PAID",
      paymentMethod: "cash",
      invoiceNumber: "LA-2025-003",
      description: "Immune Boost IV - Wellness LA",
      paidAt: new Date(timestamps.oneWeekAgo),
      createdAt: new Date(timestamps.oneWeekAgo),
      updatedAt: new Date(timestamps.oneWeekAgo),
      contact: null,
      service: null,
      organization: null,
    },
    {
      id: "pay_platform_9",
      organizationId: "org_wellness_nyc",
      ghlPaymentId: "ghl_inv_50009",
      ghlContactId: "ghl_contact_1009",
      contactId: null,
      serviceId: null,
      stripePaymentId: null,
      memberName: "Lisa Anderson",
      memberEmail: "lisa.a@example.com",
      memberPhone: "+1 (212) 555-0009",
      amount: 180.0,
      status: "PAID",
      paymentMethod: "card",
      invoiceNumber: "NYC-2025-004",
      description: "Vitamin C IV - Wellness NYC",
      paidAt: new Date(timestamps.oneWeekAgo),
      createdAt: new Date(timestamps.oneWeekAgo),
      updatedAt: new Date(timestamps.oneWeekAgo),
      contact: null,
      service: null,
      organization: null,
    },
    {
      id: "pay_platform_10",
      organizationId: "org_wellness_miami",
      ghlPaymentId: "ghl_inv_50010",
      ghlContactId: "ghl_contact_1010",
      contactId: null,
      serviceId: null,
      stripePaymentId: null,
      memberName: "Chris Martinez",
      memberEmail: "chris.m@example.com",
      memberPhone: "+1 (305) 555-0010",
      amount: 195.0,
      status: "PENDING",
      paymentMethod: null,
      invoiceNumber: "MIA-2025-003",
      description: "Athletic Performance IV - Wellness Miami",
      paidAt: null,
      createdAt: new Date(timestamps.oneWeekAgo),
      updatedAt: new Date(timestamps.oneWeekAgo),
      contact: null,
      service: null,
      organization: null,
    },
    {
      id: "pay_platform_11",
      organizationId: "org_wellness_la",
      ghlPaymentId: "ghl_inv_50011",
      ghlContactId: "ghl_contact_1011",
      contactId: null,
      serviceId: null,
      stripePaymentId: null,
      memberName: "Amanda Taylor",
      memberEmail: "amanda.t@example.com",
      memberPhone: "+1 (310) 555-0011",
      amount: 220.0,
      status: "PAID",
      paymentMethod: "card",
      invoiceNumber: "LA-2025-004",
      description: "Hangover Relief IV - Wellness LA",
      paidAt: new Date(timestamps.twoWeeksAgo),
      createdAt: new Date(timestamps.twoWeeksAgo),
      updatedAt: new Date(timestamps.twoWeeksAgo),
      contact: null,
      service: null,
      organization: null,
    },
    {
      id: "pay_platform_12",
      organizationId: "org_wellness_nyc",
      ghlPaymentId: "ghl_inv_50012",
      ghlContactId: "ghl_contact_1012",
      contactId: null,
      serviceId: null,
      stripePaymentId: null,
      memberName: "Daniel Lee",
      memberEmail: "daniel.l@example.com",
      memberPhone: "+1 (212) 555-0012",
      amount: 275.0,
      status: "REFUNDED",
      paymentMethod: "card",
      invoiceNumber: "NYC-2025-005",
      description: "Premium NAD+ Package - Wellness NYC",
      paidAt: new Date(timestamps.twoWeeksAgo),
      createdAt: new Date(timestamps.twoWeeksAgo),
      updatedAt: new Date(timestamps.twoWeeksAgo),
      contact: null,
      service: null,
      organization: null,
    },
    {
      id: "pay_platform_13",
      organizationId: "org_wellness_miami",
      ghlPaymentId: "ghl_inv_50013",
      ghlContactId: "ghl_contact_1013",
      contactId: null,
      serviceId: null,
      stripePaymentId: null,
      memberName: "Jessica Thompson",
      memberEmail: "jessica.t@example.com",
      memberPhone: "+1 (305) 555-0013",
      amount: 165.0,
      status: "PAID",
      paymentMethod: "cash",
      invoiceNumber: "MIA-2025-004",
      description: "B12 Shot + Hydration - Wellness Miami",
      paidAt: new Date(timestamps.twoWeeksAgo),
      createdAt: new Date(timestamps.twoWeeksAgo),
      updatedAt: new Date(timestamps.twoWeeksAgo),
      contact: null,
      service: null,
      organization: null,
    },
    {
      id: "pay_platform_14",
      organizationId: "org_wellness_la",
      ghlPaymentId: "ghl_inv_50014",
      ghlContactId: "ghl_contact_1014",
      contactId: null,
      serviceId: null,
      stripePaymentId: null,
      memberName: "Matthew Harris",
      memberEmail: "matthew.h@example.com",
      memberPhone: "+1 (310) 555-0014",
      amount: 210.0,
      status: "PAID",
      paymentMethod: "card",
      invoiceNumber: "LA-2025-005",
      description: "Energy Boost Package - Wellness LA",
      paidAt: new Date(timestamps.twoWeeksAgo),
      createdAt: new Date(timestamps.twoWeeksAgo),
      updatedAt: new Date(timestamps.twoWeeksAgo),
      contact: null,
      service: null,
      organization: null,
    },
    {
      id: "pay_platform_15",
      organizationId: "org_wellness_nyc",
      ghlPaymentId: "ghl_inv_50015",
      ghlContactId: "ghl_contact_1015",
      contactId: null,
      serviceId: null,
      stripePaymentId: null,
      memberName: "Ashley Clark",
      memberEmail: "ashley.c@example.com",
      memberPhone: "+1 (212) 555-0015",
      amount: 190.0,
      status: "PAID",
      paymentMethod: "card",
      invoiceNumber: "NYC-2025-006",
      description: "Glutathione IV - Wellness NYC",
      paidAt: new Date(timestamps.twoWeeksAgo),
      createdAt: new Date(timestamps.twoWeeksAgo),
      updatedAt: new Date(timestamps.twoWeeksAgo),
      contact: null,
      service: null,
      organization: null,
    },
  ] as unknown as PaymentWithRelations[];

  return <PaymentsClient payments={mockPayments} />;
}
